---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cphgderk/watchlist.carami.ro

    - /bin/mkdir -p $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/public

    - /bin/cp -R app $DEPLOYPATH/
    - /bin/cp -R config $DEPLOYPATH/
    - /bin/cp -R database $DEPLOYPATH/
    - /bin/cp -R public $DEPLOYPATH/